Python2.6 subprocess.Popen requires command arguments to be in list format
Example:

    before: command = ["git describe"]
    after:  command = ["git", "describe"]

Otherwise, an exception is raised:

    File "/usr/local/lib/python2.6/dist-packages/git.py", line 337, in describe
      p = subprocess.Popen(command, stdout=PIPE, stderr=PIPE)
    File "/usr/lib/python2.6/subprocess.py", line 633, in __init__
      errread, errwrite)
    File "/usr/lib/python2.6/subprocess.py", line 1139, in _execute_child
      raise child_exception
    OSError: [Errno 2] No such file or directory